default_platform(:android)
fastlane_require 'dotenv'

platform :android do
  lane :demo
    if (ENV["APP_REF_SHA"].length > 0)
      app_sha_ref = ENV["APP_REF_SHA"];
    end

    puts("SOMETHING - #{app_sha_ref}");
  end

  lane :undemo
    app_sha_ref = ENV["APP_REF_SHA"];

    puts("Something - #{app_sha_ref}");
  end
end
