default_platform(:android)
fastlane_require 'dotenv'

platform :android do
  lane :demo do
    if "#{ENV['APP_REF_SHA']}".length > 0
      app_sha_ref = ENV["APP_REF_SHA"];
    end

    puts("SOMETHING - #{app_sha_ref}");
  end

  lane :undemo do
    ref_sha_var = ENV["APP_REF_SHA"];
    app_sha_ref = "SOMETHING - #{(ref_sha_var.empty?) ? ref_sha_var : ''} - END";

    puts("Something - #{app_sha_ref}");
    puts("ref_sha_var: #{app_sha_ref}");
    puts("ENV VAR: #{ENV["APP_REF_SHA"]}")
  end
end
