name: Manual Trigger Lambdas
on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      environment:
        type: choice 
        options:
        - demo
        - undemo
      sha:
        type: string
      branch:
        type: string
  
jobs:
  example:
    name: Echo Branch Name
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == $WORKFLOW_ACTOR
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Sets env vars for release
        run: |
          SHA_CUT=$(echo ${{ github.sha }} | head -c 7)
          FASTLANE_LANE=${{ github.event.inputs.environment }}
          APP_REF_SHA=$(echo ${{ github.event.inputs.sha }})
          echo "THE_ENVIRONMENT=${{ github.ref_name }}-$SHA_CUT" >> $GITHUB_ENV
          echo "FASTLANE_LANE=$FASTLANE_LANE" >> $GITHUB_ENV
          echo "APP_REF_SHA=$APP_REF_SHA" >> $GITHUB_ENV
      
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run index.js
        run: |
          node index.js 

      - name: Print env
        run: |
          printenv
