name: Manual Trigger Lambdas
on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      environment:
        type: choice 
        options:
        - Development
        - Staging
        - Production
  
jobs:
  example:
    name: Echo Branch Name
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == $WORKFLOW_ACTOR
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Sets env vars for release
        run: |
          SHA_CUT=$(echo ${{ github.sha }} | head -c 7)
          echo "THE_ENVIRONMENT=${{ github.ref_name }}-$SHA_CUT" >> $GITHUB_ENV

      - name: Echo Branch Name
        run: |
          echo "👇👇👇👇👇 Environment Variabes 👇👇👇👇👇"
          printenv
