name: Manual Trigger Lambdas
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice 
        options:
        - demo
        - undemo
      sha:
        type: string
      branch:
        type: string

jobs:
  example:
    name: Echo Branch Name
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == $WORKFLOW_ACTOR
    steps:
      - name: Check if input string set
        run: |
          GHA_INPUT=$(echo "${{ github.event.inputs.branch }}" | xargs)
          { [ ! -z $GHA_INPUT ] && [ "${{ github.event_name }}" = 'workflow_dispatch' ]; } && echo "MAIN_BRANCH=$GHA_INPUT" >> $GITHUB_ENV || echo "MAIN_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.MAIN_BRANCH }}

      - name: Sets env vars for release
        run: |
          SHA_CUT=$(echo ${{ github.sha }} | head -c 7)
          FASTLANE_LANE=${{ github.event.inputs.environment }}
          APP_REF_SHA=$(echo ${{ github.event.inputs.sha }})
          echo "$MAIN_BRANCH"
          echo "THE_ENVIRONMENT=${{ github.ref_name }}-$SHA_CUT" >> $GITHUB_ENV
          echo "FASTLANE_LANE=$FASTLANE_LANE" >> $GITHUB_ENV
          echo "APP_REF_SHA=$APP_REF_SHA" >> $GITHUB_ENV
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run index.js
        run: |
          node index.js 

      - name: Print env
        run: |
          printenv
