name: Manual Trigger Lambdas
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice 
        options:
        - demo
        - undemo
      sha:
        type: string
      branch:
        type: string
  
env:
  MAIN_BRANCH: main

jobs:
  example:
    name: Echo Branch Name
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == $WORKFLOW_ACTOR
    steps:
      - name: Check if input string set
        if: github.event == 'workflow_dispatch'
        run: |
          GHA_INPUT=$(${{ github.event.inputs.branch }} | xargs)
          [ ! -z $GHA_INPUT ] && echo "MAIN_BRANCH=$GHA_INPUT" >> $GITHUB_ENV

      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.MAIN_BRANCH }}

      - name: Sets env vars for release
        run: |
          SHA_CUT=$(echo ${{ github.sha }} | head -c 7)
          FASTLANE_LANE=${{ github.event.inputs.environment }}
          APP_REF_SHA=$(echo ${{ github.event.inputs.sha }})
          echo "THE_ENVIRONMENT=${{ github.ref_name }}-$SHA_CUT" >> $GITHUB_ENV
          echo "FASTLANE_LANE=$FASTLANE_LANE" >> $GITHUB_ENV
          echo "APP_REF_SHA=$APP_REF_SHA" >> $GITHUB_ENV
      
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run index.js
        run: |
          node index.js 

      - name: Print env
        run: |
          printenv
