name: Test Builds
on:
  workflow_dispatch:
    inputs:
      sha:
        type: string
      branch:
        type: string
  
jobs:
  example:
    name: Echo Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install node modules
        run: |
          npm install
      
      - name: Run tests
        run: |
          npm test -- -u

      - name: Print env
        run: |
          printenv
