name: Import Workflow
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "The variable passed: ${{ inputs.environment }}" 

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.environment }}

      - name: Run an echo
        run: |
          PR=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Some job has been run in the gha repo"
          echo "Repo name and org name: ${{github.repository_owner}}/${{ github.event.repository.name }}"
          echo "Commit message: ${{ toJSON(github.sha) }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "GITHUB EVENT: $GITHUB_EVENT_PATH"
          echo "PR Number: $PR"
          echo "${{ toJSON(github) }}"
