name: Import Workflow
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.environment }}

      - name: Run an echo
        run: |
          echo "Some job has been run in the gha repo"
